-- MySQL Script generated by MySQL Workbench
-- Wed Mar 17 11:21:14 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema auction_test
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema auction_test
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `auction_test` DEFAULT CHARACTER SET utf8 ;
USE `auction_test` ;

-- -----------------------------------------------------
-- Table `auction_test`.`user_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auction_test`.`user_role` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `role_name` VARCHAR(45) NULL DEFAULT 'client',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `auction_test`.`auction_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auction_test`.`auction_user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_login` VARCHAR(45) NOT NULL,
  `user_password` VARCHAR(45) NOT NULL,
  `user_account` DECIMAL(10,2) NULL,
  `user_role` INT NOT NULL,
  `user_status` TINYINT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_auction_user_user_role1_idx` (`user_role` ASC) VISIBLE,
  CONSTRAINT `fk_auction_user_user_role1`
    FOREIGN KEY (`user_role`)
    REFERENCES `auction_test`.`user_role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `auction_test`.`item_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auction_test`.`item_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type_name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `auction_test`.`item_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auction_test`.`item_status` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `status_name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `auction_test`.`item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auction_test`.`item` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `item_name` VARCHAR(100) NOT NULL,
  `item_describe` VARCHAR(1000) NULL,
  `owner_id` INT NULL,
  `item_type` INT NOT NULL,
  `start_price` DECIMAL(10,2) NOT NULL,
  `item_status` INT NOT NULL DEFAULT 2,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `id_idx` (`owner_id` ASC) VISIBLE,
  INDEX `item_type_idx` (`item_type` ASC) VISIBLE,
  INDEX `fk_item_item_status1_idx` (`item_status` ASC) VISIBLE,
  CONSTRAINT `id`
    FOREIGN KEY (`owner_id`)
    REFERENCES `auction_test`.`auction_user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `item_type`
    FOREIGN KEY (`item_type`)
    REFERENCES `auction_test`.`item_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_item_item_status1`
    FOREIGN KEY (`item_status`)
    REFERENCES `auction_test`.`item_status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `auction_test`.`lot_history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auction_test`.`lot_history` (
  `id` INT NOT NULL,
  `item_id` INT NOT NULL,
  `bid_time` INT NOT NULL,
  `bid_owner_id` INT NOT NULL,
  `current_price` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_lot_history_item1_idx` (`item_id` ASC) VISIBLE,
  INDEX `fk_lot_history_user_idx` (`bid_owner_id` ASC) VISIBLE,
  CONSTRAINT `fk_lot_history_item1`
    FOREIGN KEY (`item_id`)
    REFERENCES `auction_test`.`item` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lot_history_user`
    FOREIGN KEY (`bid_owner_id`)
    REFERENCES `auction_test`.`auction_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
